import type { LucideIcon, LucideProps } from "lucide-react";
import {
  Search,
  Calendar,
  Building2,
  Home,
  Key,
  Users,
  Bell,
  X,
  ChevronDown,
  ChevronRight,
  ChevronLeft,
  ArrowLeft,
  ArrowRight,
  Eye,
  EyeOff,
  Heart,
  MessageSquare,
  Send,
  FileText,
  Image as ImageIcon,
  Video,
  DollarSign,
  CreditCard,
  LogOut,
  User,
  Settings,
  MapPin,
  Bed,
  Bath,
  Square,
  Grid,
  List,
  Check,
  Plus,
  Minus,
  Star,
  Menu,
  Facebook,
  Twitter,
  Instagram,
  Linkedin,
  Mail,
  Phone,
  Link as LinkIcon,
  Upload,
  Download,
  Filter,
  SortAsc,
  HelpCircle,
  AlertCircle,
  CheckCircle,
  XCircle,
  PlayCircle,
  Paperclip,
  MoreVertical,
  Edit,
  Trash2,
  Share2,
} from "lucide-react";

// Re-export commonly used icons
export {
  Search as SearchIcon,
  Calendar as CalendarIcon,
  Building2 as BuildingIcon,
  Home as HomeIcon,
  Key as KeyIcon,
  Users as UsersIcon,
  Bell as NotificationIcon,
  X as CloseIcon,
  ChevronDown,
  ChevronRight,
  ChevronLeft,
  ArrowLeft,
  ArrowRight,
  Eye as EyeIcon,
  EyeOff as EyeOffIcon,
  Heart as HeartIcon,
  MessageSquare as ChatIcon,
  Send as SendIcon,
  FileText as DocumentIcon,
  ImageIcon,
  Video as VideoIcon,
  DollarSign as MoneyIcon,
  CreditCard as CardIcon,
  LogOut as LogoutIcon,
  User as UserIcon,
  Settings as SettingsIcon,
  MapPin as LocationIcon,
  Bed as BedIcon,
  Bath as BathIcon,
  Square as SquareIcon,
  Grid as GridIcon,
  List as ListIcon,
  Check as CheckIcon,
  Plus as PlusIcon,
  Minus as MinusIcon,
  Star as StarIcon,
  Menu as MenuIcon,
  Facebook as FacebookIcon,
  Twitter as TwitterIcon,
  Instagram as InstagramIcon,
  Linkedin as LinkedInIcon,
  Mail as MailIcon,
  Phone as PhoneIcon,
  LinkIcon,
  Upload as UploadIcon,
  Download as DownloadIcon,
  Filter as FilterIcon,
  SortAsc as SortIcon,
  HelpCircle as HelpIcon,
  AlertCircle,
  CheckCircle as CheckCircleIcon,
  XCircle as XCircleIcon,
  PlayCircle as PlayIcon,
  Paperclip as PaperClipIcon,
  MoreVertical as MoreIcon,
  Edit as EditIcon,
  Trash2 as TrashIcon,
  Share2 as ShareIcon,
};

export type { LucideIcon, LucideProps };

// Icon wrapper component
export const Icon = ({
  icon: IconComponent,
  className,
  ...props
}: {
  icon: LucideIcon;
  className?: string;
} & LucideProps) => {
  return <IconComponent className={className} {...props} />;
};
